### ISSUE TITLE
bug: [pet] wrong section names when setting configuration

### ISSUE THREAD

**Issue by mmequignon** [nix-community/home-manager#2413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I'm trying to configure `pet`, I'd like to set a Gitlab section to sync my snippets.
The issue is that, when doing so, instead of creating a new [Gitlab] section in the resulting toml fil, it creates a [General.Gitlab] section instead.

I.E.

```nix
      pet = {
        enable = true;
        settings = {
          General = {
            backend = "Gitlab";
            editor = "nvim";
          };
          GitLab = {
            access_token = "${PET_TOKEN}";
            file_name = "pet-snippets.toml";
            id = "";
            visibility = "public";
          };
        };
      };
```
```toml
[General]
selectcmd = "fzf"
snippetfile = "/home/matthieu/.config/pet/snippet.toml"

[General.General]
backend = "Gitlab"
editor = "nvim"

[General.GitLab]
access_token = "Kp47Pa5iusRZ8sJVYGbQ"
file_name = "pet-snippets.toml"
id = ""
visibility = "public"
```

The issue is here https://github.com/nix-community/home-manager/blob/master/modules/programs/pet.nix#L82-L97

I can try to handle that on my own.

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 5.14.9, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11pre324423.34ad3ffe08a, home-manager"`
 - channels(matthieu): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
