### ISSUE TITLE
bug: i3status-rs weather block unusable due to unquoted curly braces in TOML configuration syntax

### ISSUE THREAD

**Issue by Slime90** [nix-community/home-manager#2834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am unable to configure the Weather block using the i3status-rust.nix module, as the service line has formatting that results in nix failing to properly evaluate and generate the TOML. Formatting for this (required) line taken directly from the blocks.md documentation file in the i3status-rs repo.

```nix
        blocks = [
          {
            block = "focused_window";
            max_width = 50;
            show_marks ="visible";
          }
          {
            block = "weather";
            format = "{weather} ({location}) {temp}, {wind} m/s {direction}";
            service = { name = "openweathermap", api_key = "XXX", city_id = "5398563", units = "metric" };
          }
```

```
❯ switch
error: syntax error, unexpected ',', expecting ';', at /home/<username>/.config/nixpkgs/configs/i3status-rs.nix:18:48
```

### Maintainer CC

@ncfavier @sephii @rycee @happysalada @workflow @ivan

### System information

```markdown
❯ nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.101, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(<username>): `"home-manager-21.11"`
 - channels(root): `"nixos-21.11.336103.40ef692a55b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by ncfavier** [comment]
Well you can't use TOML syntax in a Nix file.

Once you convert the line to valid Nix, you get a config file that looks like this:

```toml
[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "weather"
format = "{weather} ({location}) {temp}, {wind} m/s {direction}"

[block.service]
api_key = "XXX"
city_id = "5398563"
name = "openweathermap"
units = "metric"
```

Which I suppose should be equivalent to the TOML you showed.
