### ISSUE TITLE
Helix: support configuring grammars

### ISSUE THREAD

**Issue by cherryblossom000** [nix-community/home-manager#2871]
### Support configuring tree-sitter grammars in `languages.toml` for Helix.

Docs: https://docs.helix-editor.com/languages.html#tree-sitter-grammars

```toml
[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "a250c4582510ff34767ec3b7dcdd3c24e8c8aa68" }
```

The `use-grammars` key should also be supported, which controls which grammars are fetched and built (if omitted all grammars are used).

```toml
use-grammars = { only = [ "rust", "c", "cpp" ] }
# or
use-grammars = { except = [ "yaml", "json" ] }
```
