### ISSUE TITLE
bug: Helix: Incorrect TOML Configuration Generated

### ISSUE THREAD

**Issue by billksun** [nix-community/home-manager#2907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I am trying to override the language configuration for Helix. I want to produce the following `languages.toml`:
```toml
[[language]]
name = "haskell"
language-server = { command = "haskell-language-server", args = [] }
```
I have the following in my `home-nix`:
```nix
  programs.helix = {
    enable = true;
    languages = [
      {
        name = "haskell";
        language-server = { 
          command = "haskell-language-server";
          args = [];
        };
      }      
    ];
  };
```
But it instead produces this in `languages.toml`:
```toml
[[language]]
name = "haskell"

[language.language-server]
args = []
command = "haskell-language-server"
```

### Maintainer CC

@Philipp-M 

### System information

```markdown
 - system: `"x86_64-linux"`
 - host os: `Linux 5.15.34, NixOS, 22.05 (Quokka), 22.05pre369988.1ffba9f2f68`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.8.0pre20220411_f7276bc`
 - channels(root): `"nixos"`
 - channels(bill): `"home-manager"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Philipp-M** [comment]
```toml
[[language]]
name = "haskell"
language-server = { command = "haskell-language-server", args = [] }
```
and 
```toml
[[language]]
name = "haskell"

[language.language-server]
args = []
command = "haskell-language-server"
```
is actually equivalent in what is interpreted by helix. Is there any issue with it?

Might this: https://github.com/helix-editor/helix/issues/1000 be related?

Other issues/PRs regarding this issue:
https://github.com/helix-editor/helix/pull/2145
https://github.com/helix-editor/helix/pull/2215

**Comment by billksun** [comment]
Oh, I didn't know that! But indeed Helix seem to be okay with that config.

I'm not too familiar with TOML, but how does the parser know to apply the `haskell-language-server` config to `haskell` and not another language? I assumed they needed to be in the same block. Or is the ordering here significant as well? For example, if I had:

```toml
[[language]]
name = "haskell"

[language.language-server]
args = []
command = "python-lsp-server"

[[language]]
name = "python"

[language.language-server]
args = []
command = "haskell-language-server"
```

The Python language server would be grouped with `haskell` and the Haskell language server would be groupe with `python`?
