### ISSUE TITLE
bug: No way to override the language-server command in programs.helix

### ISSUE THREAD

**Issue by aniketd** [nix-community/home-manager#3299]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

For `programs.helix`, trying to override the default `langauge-server` `command` for `haskell`.

Configuration:
```nix
helix {
  enable = true;
  ...
  languages = [
    {
      name = "haskell";
      auto-format = false;
      language-server = { command = "haskell-langauge-server"; };
    }
  ];
};
```
This results in the TOML
```toml
[[language]]
auto-format = false
name = "haskell"

[langauge.language-server]
command = "haskell-langauge-server"
```
But, the expectation of `helix` is to parse something like the following, as per the [documentation](https://docs.helix-editor.com/languages.html#language-configuration)
```toml
[[language]]
auto-format = false
name = "haskell"
language-server = { command = "haskell-language-server" }
```
"stringifying" the `attrs` results in the value appearing quoted ("") in the resulting TOML file, and `helix` does not like it.

### Maintainer CC

@Philipp-M 

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 5.15.70, NixOS, 22.05 (Quokka), 22.05.3389.9cac4585028`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.8.1`
- channels(root): `"home-manager-22.05.tar.gz, nixos-22.05, unstable"`
- channels(aniketd): `""`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by Philipp-M** [comment]
> `helix` does not like it.

Is something not working?
Looks like https://github.com/nix-community/home-manager/issues/2907

This *should* be equivalent to the syntax you mention.
Also checkout https://toml.io/en/v1.0.0#array-of-tables

**Comment by aniketd** [comment]
@Philipp-M I confirmed by taking the configuration out of `home-manager` and doing it manually, that the issue is on the side of `helix`. And also, apologies for the incorrect assumption. I did have a hunch that it should be equivalent TOML. Sorry for taking up your time.

**Comment by aniketd** [comment]
Just to be clear... making the file read like
```toml
[[language]]
name = "haskell"
...
language-server = { command = "haskell-language-server" }
```
manually, did not make any difference, as `helix` still thinks the command is `haskell-language-server-wrapper` (the default). Adding the configuration somehow does not seem to make any difference to `hx --health haskell` output, which still prints out the default value. So I'm guessing my version of `helix` parses correctly, but silently ignores the override.
