### ISSUE TITLE
helix languages not generate proper toml, grammers not supported

### ISSUE THREAD

**Issue by realsnick** [nix-community/home-manager#3425]
https://github.com/nix-community/home-manager/blob/948d1f8a5cef55a281d4f5d17f3b79df6c82fce1/modules/programs/helix.nix#L44

```nix
languages = [
  { 
    name = "nix";
    language-server = { command = "nil"; };
];
```

is generated to 
```toml
[[language]]
name = "nix"
[language.language-server]
command = "nil"
```

correct behavior should generate the following `toml`
```toml
[[language]]
name = "nix"
language-server = { command = "nil" }
```

in addition, there is no way to declare a `grammer`

should generate a proper `toml` similar to below
```toml
[[language]]
name = "nix"
scope = "source.nix"
injection-regex = "nix"
file-types = ["nix"]
shebangs = []
roots = []
auto-format = true
formatter = { command = "nixpkgs-fmt" }
comment-token = "#"
language-server = { command = "nil" }
indent = { tab-width = 2, unit = "  " }

[[grammar]]
name = "nix"
source = { git = "https://github.com/cstrahan/tree-sitter-nix", rev = "1b69cf1fa92366eefbe6863c184e5d2ece5f187d" }⏎      
```
