### ISSUE TITLE
bug: unable to configure auto-pairs in helix

### ISSUE THREAD

**Issue by jtrees** [nix-community/home-manager#4320]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm trying to configure custom auto-pairs in helix but I'm unable to produce a toml file that helix can read. The docs describe it like this:

```toml
[[language]]
name = "rust"

[language.auto-pairs]
'(' = ')'
```

But all my attempts to configure this manually have resulted in the following error:

```
Bad language config: data did not match any variant of untagged enum AutoPairConfig
in `language.auto-pairs`
```

### Details

Here's what I've tried so far:

#### (1) Double Quotes, No Escapes

```nix
{ name = "nix";
  auto-pairs = { "{" = "};"; };
}
```

=>

```toml
[[language]]
name = "nix"

[language.auto-pairs]
"{" = "};"
```

#### (2) Double Quotes, Double Backslash

```nix
{ name = "nix";
  auto-pairs = { "\\{" = "\\};"; };
}
```

=>

```toml
[[language]]
name = "nix"

[language.auto-pairs]
"\\{" = "\\};"
```

#### (3) Double Quotes, Single Backslash

```nix
{ name = "nix";
  auto-pairs = { "\{" = "\};"; };
}
```

=>

```toml
[[language]]
name = "nix"

[language.auto-pairs]
"{" = "};"
```

### Additional Notes

I am aware that this is probably an upstream bug in nixpkgs toml format implementation. Perhaps some kind of workaround is possible?

### Maintainer CC

@dmarcoux @KiruyaMomochi @Philipp-M

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.1.41, NixOS, 23.05 (Stoat), 23.05.2441.b7cde1c47b73`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.3`
 - channels(root): `"home-manager-23.05.tar.gz, nixos-23.05, nixos-unstable"`
 - channels(josh): `"release-22.11.tar.gz-22.11.tar.gz"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
