### ISSUE TITLE
bug: broot config unable to override imports

### ISSUE THREAD

**Issue by cgahr** [nix-community/home-manager#4603]
### Are you following the right branch?

- [X] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue description

I used the following config for broot:
```nix
programs.broot.settings = {
  imports = [ "verbs.hjson" ];
}
```
The generated config is
```toml
content_search_max_file_size = "10MB"
imports = [
  "verbs.hjson", 
  {file = "skins/dark-blue.hjson", luma = ["dark", "unknown"]}, 
  {file = "skins/white.hjson", luma = "light"}, 
  "verbs.hjson"
]
modal = false
show_selection_mark = true
verbs = []

[skin]

[special_paths]
"/media" = "no-enter"
```
The problem is, that it is impossible to override the default value for `imports`. In general, a user might want to set
```toml
imports = []
```
to remove all imports. Afaik, this is not possible right now.

Also, and this is minor, some of the existing default options are not documented:
- `content_search_max_file_size`
- `show_selection_mark`
- `special_paths`

### Maintainer CC

@aheaume @dermetfan 

### System information

```markdown
- system: `"x86_64-linux"`
- host os: `Linux 6.2.0-35-generic, Ubuntu, 22.04.3 LTS (Jammy Jellyfish), nobuild`
- multi-user?: `yes`
- sandbox: `yes`
- version: `nix-env (Nix) 2.16.1`
- channels(root): `"nixpkgs"`
- nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
