### ISSUE TITLE
Bug Report: Breaking Change in `aerospace` Configuration after Commit 95861b5

### ISSUE THREAD

**Issue by phucleeuwu** [nix-community/home-manager#6790]
## Commit

https://github.com/nix-community/home-manager/commit/95861b5d9fc73f080b385776167c3dd2874e355b

## Summary

The above commit introduces a breaking change to the `aerospace` module which causes previously working configurations to fail validation.

Specifically, this Aerospace configuration:

```nix
on-window-detected = [
  {
    "if".app-name-regex-substring = "wezterm|kitty|ghosty";
    run = "move-node-to-workspace W";
  }
  {
    "if".app-name-regex-substring = "arc";
    run = "move-node-to-workspace A";
  }
  {
    "if".app-name-regex-substring = "spotify";
    run = "move-node-to-workspace 2";
  }
  {
    "if".app-name-regex-substring = "finder";
    run = "move-node-to-workspace E";
  }
];
```
Now fails with the following error:
```
Failed to parse /Users/phuc/.config/aerospace/aerospace.toml

on-window-detected[0].if.app-name-regex-substring: Unknown key

on-window-detected[1].if.app-name-regex-substring: Unknown key

on-window-detected[2].if.app-name-regex-substring: Unknown key

on-window-detected[3].if.app-name-regex-substring: Unknown key
```

**Comment by andre4ik3** [comment]
It is because of PR #6778, which makes the generated TOML look like this:

```toml
[[on-window-detected]]
"if.app-id" = "com.apple.iphonesimulator"
run = ["layout floating"]
```

Which Aerospace fails to load. Before it looked like this:

```toml
[[on-window-detected]]
run = ["layout floating"]

[on-window-detected.if]
app-id = "com.apple.iphonesimulator"
```

Which is weird but works. How it should really look is this:

```toml
[[on-window-detected]]
if.app-id = "com.apple.iphonesimulator"
run = ["layout floating"]
```

For now, a workaround is just to pin Home-Manager to a commit before that one. E.g.

```
inputs.home-manager.url = "github:nix-community/home-manager/80ae77eed3a3b48597ec9c1d23ce6e4784214071";
```
